version: '3.8'
services:
  # container prisma
  dev-database:
    container_name: dev-database
    image: postgres:15.0
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: db-app-chat
    networks:
      - nestjs-network

  #container-nestjs
  nestjs-app:
    container_name: dev-nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - nestjs-network
networks:
  nestjs-network:
